### ISSUE TITLE
ref_RowPopulations: combined Population IDs = [1048, 1148, 1248] should be deleted

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#1104]
Hi @MollyMcEvilley ,

According to Spec, Subpopulation 48 is allowed to be in combination with each of the parent populations = [0, 13, 14, 15].
So Population IDs = [1048, 1148, 1248] are not valid.
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/245b430e-d282-43ff-8564-ebc3b4e06547)

Could you please remove hightlighted rows from ref_RowPopulations table?
![image](https://github.com/HMIS/LSASampleCode/assets/28144855/7e11d814-379a-43df-8cfe-c026a1f52d75)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
This is a specs issue -- the parent populations for PopID 48 include 0 and 10-15.  Commit forthcoming.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

As it was an issue in the Spec, Could you please add Population IDs = [1048, 1148, 1248] rows in LSA Data Dictionary FY2023 Population List? Thank you!
