### ISSUE TITLE
Sample Code (3.3.1): ExitDate on either OperatingEnd or HMISEnd

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#1325]
Hi @MollyMcEvilley ,

Just want to confirm with you that a case when ExitDate on either OperatingEnd or HMISEnd is valid for us, If no, then Sample Code requires an update:

![image](https://github.com/user-attachments/assets/5bd959c5-4905-4e71-95fa-bf1dd15d7cce)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, that's valid!
