### ISSUE TITLE
LSA Spec: question about Export CSV version

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#675]
Hi @MollyMcEvilley ,

The most recent Export CSV FY2022 version is v1.2: https://www.hudhdx.info/Resources/Vendors/HMIS_CSV_Specifications_FY2022_v1.2_clean.pdf 

I wonder if LSA spec should be corrected as well?

![image](https://user-images.githubusercontent.com/28144855/136207591-0c2ad098-10ed-4db7-ab02-c95ae66bace6.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, thank you -- commit forthcoming.
