### ISSUE TITLE
Section 4.2: Spec was updated, but Sample Code wasn't

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#687]
HI @MollyMcEvilley ,

Not sure why it is not highlighted in the Spec, but Spec FY2021 is different from Spec FY2019 with one sentence I highlighted:
![image](https://user-images.githubusercontent.com/28144855/136404831-488fd542-9535-4fb5-a84c-3f56be43363d.png)

But there is no _Project.OperatingEndDate >= ReportStart or Project.OperatingEndDate is NULL_ restriction in Sample Code:
![image](https://user-images.githubusercontent.com/28144855/136404910-0c7b1398-efd6-4b6b-995a-05dfa5c5ed4a.png)

NOTE: lsa_Project was updated in FY2021 to include projects active since hp.OperatingEndDate >= '10/1/2012' ( In FY2019 the restriction was hp.OperatingEndDate >= rpt.ReportStart).

Please advise.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
The end date of the funder record(s) should be consistent with the project end date, if there is one, so the sample code covers the requirement.  If a funding period extends past the operating period for the project, that would be weird -- and worthy of explanation or correction.
