### ISSUE TITLE
Section 4.5: Spec was updated, but Sample Code wasn't

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#688]
Hi @MollyMcEvilley ,

Not sure why it is not highlighted in the Spec, but Spec FY2021 is different from Spec FY2019 with one sentence I highlighted:
![image](https://user-images.githubusercontent.com/28144855/136407612-9c9e6ea0-4840-4a7b-bf5c-fcbc7ccd1624.png)

I wonder do we need to include **Project.OperatingEndDate >= ReportStart or Project.OperatingEndDate is NULL** in the Sample Code?

![image](https://user-images.githubusercontent.com/28144855/136407328-d7ab70ed-ba63-497e-890b-9768d7172587.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
This isn't a difference in logic -- Inventory records were only required for active projects last year.  As with the Funder records, it would be weird if an Inventory record remained active after a project end date -- something to correct or explain and not something to filter out with LSA logic.
