### ISSUE TITLE
Incorrect join

### ISSUE THREAD

**Issue by eanders** [HMIS/LSASampleCode#690]
Hi Molly,
I _think_ this should be `hhid.EnrollmentID = nbn.EnrollmentID`  (or HouseholdID = HouseholdID).
https://github.com/HMIS/LSASampleCode/blob/ee9a05715afde520bba7096f9caffc51489b4ae8/03_02%20to%2003_06%20HMIS%20Households%20and%20Enrollments.sql#L233

We're hitting issues with NbN clients.  (This is the result of finally getting to digging into the source of: https://github.com/HMIS/LSASampleCode/issues/686)

**Comment by MollyMcEvilley** [comment]
Join should be on HouseholdID... commit forthcoming.
