### ISSUE TITLE
HDX rejected file

### ISSUE THREAD

**Issue by eanders** [HMIS/LSASampleCode#691]
The HDX (https://testing.hudhdx2.info) is rejecting the sample LSA CSV file from the Vendor Hub with the attached issues.
[module.upload-errors.pdf](https://github.com/HMIS/LSASampleCode/files/7307289/module.upload-errors.pdf)
 
In testing our own export, we're able to clear all but one issue.  The HDX is complaining about a header in LSAPerson.csv.
`Bad column header in LSAPerson: column header is 'HHChronicEST', should be 'AHARAdultEST'.`
We've adjusted and double checked the headers against the sample result and table creation code.  Both fields exist in our export, and if we adjust to match the error report it complains about a different field.  

Could you double check the header check logic on the HDX?

**Comment by MollyMcEvilley** [comment]
The AHARAdult columns were out of order in 01 Temp Reporting and Reference Tables -- commit forthcoming.

**Comment by eanders** [comment]
I'm still getting a rejection from the HDX.  Can you confirm what the headers in LSAPerson.csv should be?  Here's what I'm currently sending:

```
RowTotal,Gender,Race,Ethnicity,VetStatus,DisabilityStatus,CHTime,CHTimeStatus,DVStatus,ESTAgeMin,ESTAgeMax,HHTypeEST,HoHEST,AdultEST,HHChronicEST,HHVetEST,HHDisabilityEST,HHFleeingDVEST,HHAdultAgeAOEST,HHAdultAgeACEST,HHParentEST,AC3PlusEST,AHAREST,AHARHoHEST,AHARAdultEST,RRHAgeMin,RRHAgeMax,HHTypeRRH,HoHRRH,AdultRRH,HHChronicRRH,HHVetRRH,HHDisabilityRRH,HHFleeingDVRRH,HHAdultAgeAORRH,HHAdultAgeACRRH,HHParentRRH,AC3PlusRRH,AHARRRH,AHARHoHRRH,AHARAdultRRH,PSHAgeMin,PSHAgeMax,HHTypePSH,HoHPSH,AdultPSH,HHChronicPSH,HHVetPSH,HHDisabilityPSH,HHFleeingDVPSH,HHAdultAgeAOPSH,HHAdultAgeACPSH,HHParentPSH,AC3PlusPSH,AHARPSH,AHARHoHPSH,AHARAdultPSH,ReportID
```

**Comment by eanders** [comment]
Hmm, looks like maybe AHARAdultEST and AHARAdultRRH snuck in from tlsa_Person.  Closing for now.
