### ISSUE TITLE
Section 5.7: Sample Code was updated, but Spec wasn't

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#692]
Hi @MollyMcEvilley ,

`or (chn.ProjectType = 13 and chn.MoveInDate = chn.ExitDate and cal.theDate = chn.MoveInDate)` was removed from Sample Code Step 5.7.

But Spec still have MoveInDate logic for ProjectType = 13
![image](https://user-images.githubusercontent.com/28144855/136794392-7fa478ac-e032-457f-a1da-a06dc2cd6b76.png)

Should Spec also be updated?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, thanks... This is no longer relevant -- with the adjusted **ExitDate** for these enrollments, there will be no records where **MoveInDate** = **ExitDate**.  Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/137141855-af96617c-5fc9-4072-8744-3cd2db53d020.png)
