### ISSUE TITLE
Section 5.8.3: Possible issue with Sample Code

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#693]
Hi @MollyMcEvilley ,

In Sample Code `ProjectType not in (1,8)` was replaced with `LSAProjectType not in (1,8)`. But what is about ES NbN projects? Shouldn't it be  `LSAProjectType not in (0,1,8)`?

![image](https://user-images.githubusercontent.com/28144855/136794565-f99f72fa-95d6-4d3d-b1e5-2cca9ab8c7a1.png)

Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes -- commit forthcoming.
