### ISSUE TITLE
Section 5.8.2: Sample Code was updated, but not Spec

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#694]
Hi @MollyMcEvilley ,

Sample Code for Step 5.8.2 was updated:
- `inner join tlsa_HHID hhid on hhid.HouseholdID = chn.HouseholdID` was added
- `hmis_Services bn on bn.EnrollmentID = chn.EnrollmentID` was changed to `hmis_Services bn on bn.EnrollmentID = hhid.EnrollmentID`

But nothing was changed in the Spec:
- `tlsa_HHID` table wasn't added to [Relevant Data] section
- no info that hmis_Services should be used for hhid.EnrollmentID and not for chn.EnrollmentID
![image](https://user-images.githubusercontent.com/28144855/136794694-027030ed-db6b-4b42-aa2a-bc4566d2eb2b.png)

Could you please take a look and advise?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
The issue here was in the sample code -- the bednights should be for the person, not the HoH (if they differ), and the join to tlsa_HHID should not be there.  Commit forthcoming.

![image](https://user-images.githubusercontent.com/6156815/137144803-29c747dd-3892-48ca-bcf9-8cf81e701e7b.png)
