### ISSUE TITLE
HHChronic: parentheses are missing in the Sample Code

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#695]
Hi @MollyMcEvilley ,

`n.RelationshipToHoH = 1 or n.ActiveAge between 18 and 65` should be in parentheses. Could you please take a look?

![image](https://user-images.githubusercontent.com/28144855/136794972-13cb7bb8-a084-464b-a926-54f798a31cf7.png)

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
Yikes.  Commit forthcoming.
