### ISSUE TITLE
HHChronic: DisabilityStatus = 1 issue

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#696]
Hi @MollyMcEvilley,

Either Sample Code or Spec has an issue with DisabilityStatus = 1 usage for HHChronic.

`DisabilityStatus = 1` is used as a mandatory restriction in Spec for LSA HHChronic Value, but it is not used in the Sample Code.

![image](https://user-images.githubusercontent.com/28144855/136795984-01be26f3-042b-4271-80ed-628df3edce88.png)

Could you please take a look?

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
Commit forthcoming!
