### ISSUE TITLE
HHType(EST/RRH/PSH): extra "and" in the spec

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#697]
Hi @MollyMcEvilley ,

Is there any "and" condition needed?

![image](https://user-images.githubusercontent.com/28144855/136798335-d231b3ee-efd8-4cae-95fc-85498c57f9d8.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
No -- commit forthcoming.
