### ISSUE TITLE
Section 11: new LSAProjectType = 0 is missing in Sample Code for Emergency Shelter projects

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#702]
Hi @MollyMcEvilley ,

I wonder if `LSAProjectType = 0` wasn't included on purpose when `ProjectType in (1,8)` was replaced with `LSAProjectType in (1,8)`.

Could you please take a look at:
- HomelessDate1 
- HomelessDate3 
- TimesHomeless1 
- TimesHomeless3 
- MonthsHomeless1 
- MonthsHomeless3 

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
Alas, no, it was excluded accidentally.  Commit forthcoming to include LSAProjectType 0 in the subqueries for those columns.
