### ISSUE TITLE
Step 8.3.15 and Step 8.3.33: Issue in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#704]
Hi @MollyMcEvilley ,

There is no way HoHRace can be 8 or 9. Maybe you wanted to use `hh.HoHRace not in (98,99)`? Because now HoHRace = 98 is counted as 'Multi-Racial'.

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/136973857-d3263846-bd62-47b3-a5d8-93a5890766a9.png)
![image](https://user-images.githubusercontent.com/28144855/136974973-056a8197-51b6-4706-b24f-aad39825b098.png)

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/136974521-ad460857-e7c0-429e-9c90-77aa2d455bf4.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Commit forthcoming.
