### ISSUE TITLE
Section 8.9: lsa_Calculated.ReportRow discrepancy (Spec)

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#715]
Hi!

Could you please confirm that ReportRow between 18 and 22 and ReportRow = [63, 64] should be exported as lsa_Calculated.ReportRow = 23?
![image](https://user-images.githubusercontent.com/28144855/137130825-0277dd8d-61c1-4472-a97b-27e63ab61a25.png)

Thank you!
Natalie

**Comment by nataliesus** [comment]
If Spec is correct, could you please take a look if Sample Code should be corrected?
Maybe `and (rv.RowID not between 18 and 22 or ex.ExitFrom = (rv.RowID - 16))` should be replaced with `and (rv.RowID not between 18 and 23 or ex.ExitFrom = (rv.RowID - 16))` so `ExitFrom = RowID - 16` should work for RowID = 23 as well? But in this case it works correctly for ReportRow between 18 and 22, but not for ReportRow = 63 and 64. Please advise.
![image](https://user-images.githubusercontent.com/28144855/137144428-1333caa1-60e5-4f2c-9280-da1669be79e8.png)

Also, if Spec is correct, then it is a bit confusing that it states "**For each ReportRow listed below**, Value = the average of ..."
![image](https://user-images.githubusercontent.com/28144855/137145094-d08d4846-bb00-4f9b-adbb-1932cca55f58.png)

**Comment by MollyMcEvilley** [comment]
Fortunately, it is the specs that are incorrect here -- the only **ReportRow** relevant to section 8.9 is 23, so the sample code is fine... Commit forthcoming.
![image](https://user-images.githubusercontent.com/6156815/137165269-932265e0-9eb3-4603-ad62-0e927a6772c7.png)

(I mean, it's not fortunate that the specs are wrong -- but it's easier to fix the specs than to incorporate the other rows' logic into the sample code... 😉)
