### ISSUE TITLE
Step 8.8: parentheses are missing in the Sample Code

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#716]
Hi @MollyMcEvilley,

I believe `ph.HHType = 0 or ph.HHType = ex.HHType` should be in parentheses. Could you please take a look?

![image](https://user-images.githubusercontent.com/28144855/137131575-17d543ea-e6cb-427f-9f58-9bc08daa8d2f.png)

Thank you!
Natlaie

**Comment by MollyMcEvilley** [comment]
You are absolutely correct!
