### ISSUE TITLE
Section 9.3: Spec needs corrections

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#717]
Hi @MollyMcEvilley !

**1.** [HHDisability] is used in "Household Type and Populations" section, so it should be included in Source -> tlsa_HHID
**2.** I wonder if "HHType" column name in "Household Type and Populations" section should be renamed as "ActiveHHType"?
![image](https://user-images.githubusercontent.com/28144855/137160624-c4ce6672-1791-492a-9b71-ab67b52c45de.png)
**3.** You wrote "WRT veteran household types... I added 99 to the specs." under https://github.com/HMIS/LSASampleCode/issues/706#issuecomment-942382997.
Could you please update it for Section 9.3 as well?
![image](https://user-images.githubusercontent.com/28144855/137161456-9defd7c8-c57f-4458-9799-c59d5479f33c.png)

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Yes, thank you!! Commit forthcoming.
