### ISSUE TITLE
Step 3.3.1: follow-up question for #677

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#721]
Hi @MollyMcEvilley ,

It is follow-up for #677.

**Q1.**
In Sample Code there is p.OperatingEndDate **<=** rpt.ReportEnd.
![image](https://user-images.githubusercontent.com/28144855/136359372-8e92497b-40a8-4d37-9e07-1ee384f7d768.png)

but in Spec it is if Project.OperatingEndDate **<** ReportEnd, so Project.OperatingEndDate == ReportEnd is ignored.
![image](https://user-images.githubusercontent.com/28144855/137292468-322c8236-cb78-472a-8950-d10b20841001.png)

Could you please take a look?

**Q2.**
Also, in Sample Code Effective Exit Date = null for [p.ProjectType = 13 and hoh.MoveInDate = hx.ExitDate and hx.ExitDate = rpt.ReportEnd] but this scenario is not listed in the updated instructions your provided in your last comment.
![image](https://user-images.githubusercontent.com/28144855/136360454-9bb69a1e-a438-467a-ab65-534d2da98acf.png)

**Q3.**
For "MoveInDate = ExitDate", do we need to use "Effective Move-In Date" or "HMIS Move-In Date"?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Q1: Specs updated consistent with sample code, which is correct.
Q2:  Added clarification/reiteration that any information dated after ReportEnd is not relevant.
Q3:  The reference in this instance is to HMIS Move-In Date.

Commit forthcoming.
