### ISSUE TITLE
Sample Code: step 9.1.7 and step 9.1.8 consistency question

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#722]
Hi @MollyMcEvilley ,

I just wonder why tlsa_HHID.ActiveHHType is used is some cases only.

I.e. both "Chronically Homeless" and "Disabled Adult or HoH" should be checked for ActiveHHType = [0,1,2,3,99].
But in Sample code `tlsa_HHID.ActiveHHType in (select HHType from ref_PopHHTypes where PopID = NNN )` is used for `HHFleeingDV = 1` and not used for `HHDisability = 1`

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/137293299-94625112-acdb-4766-bb3d-167f8282a4bf.png)

**Spec:**
![image](https://user-images.githubusercontent.com/28144855/137293452-07f11ff3-17a0-40fd-ad69-b4db274276aa.png)

Just want to understand the difference.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Upon review, there is no good reason for the inconsistency -- commit forthcoming.

- For the populations where household type matters, it's simple enough to put it in the 'INSERT TO tlsa_CountPops' statement -- I've gone through and done that.
- For populations where it doesn't matter (e.g. FleeingDV), there's no point in checking it -- I've gone through and removed the checks where relevant.
