### ISSUE TITLE
Section 9.3: issue in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#725]
Hi @MollyMcEvilley ,

**1.**
Parentheses are missing:
![image](https://user-images.githubusercontent.com/28144855/137309462-db51c6b4-c65a-4207-bd2d-6ab9ed068e32.png)

**2.** Could you please double-check `case when rv.RowID = 53 then hhid.HouseholdID else null end` in GROUP BY?
![image](https://user-images.githubusercontent.com/28144855/137311040-4230b60d-4786-4533-a2ca-3578864ae5ab.png)
I have some doubts because, according to Spec:
- for row 53 we should count `Distinct PersonalIDs in tlsa_Enrollment`
- for row 54 we should count `Distinct combinations of HoHID/ActiveHHType in tlsa_HHID`
![image](https://user-images.githubusercontent.com/28144855/137311190-dac20bfc-cd92-4649-8222-2f83c48c9087.png)
But it is possible that I miss something important.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1. The commit above adds the required parentheses.
2. Remains open at the moment.

**Comment by MollyMcEvilley** [comment]
Re: your #2 -- that makes a huge and helpful difference -- thank you -- commit forthcoming.
