### ISSUE TITLE
Step 9.1.17: Race Issue in Sample Code

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#728]
Hi @MollyMcEvilley ,

There are duplicate `lp.Race = 5 and lp.Ethnicity <> 1` conditions in CASE statement that causes issue with PopIDs.
![image](https://user-images.githubusercontent.com/28144855/137328444-5bbec03f-b3d2-4ce8-ac16-c7e77e80616f.png)

You need to remove the first `WHEN .. THEN ..` and update all PopIDs to match the spec:
![image](https://user-images.githubusercontent.com/28144855/137329308-d6bb83b8-2727-4e67-99e6-20237c0ff49e.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
That code was a mess -- thank you -- commit forthcoming.
