### ISSUE TITLE
Step 9.1.22: question about subpopulation id

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#731]
Hi @MollyMcEvilley ,

Please correct me if step 9.1.22 in Sample Code is about Subpopupation from Spec:
![image](https://user-images.githubusercontent.com/28144855/137345206-0128feff-293e-49e9-8c32-c996fbb59bdb.png)

I wonder why rp.RowMax <> 64 is used in Sample Code. Shouldn't we use `rp.RowMax <= 71`.
![image](https://user-images.githubusercontent.com/28144855/137345390-13caa8b3-ceaf-49d2-beda-3f9474074189.png)

I can be mistaken, but shouldn't p1.PopID be only [50, 51, and 52] and p1.PopID between 53 and 71? Maybe the whole WHERE statement should be rewritten? Please correct me.

Thank you,
Natalie

**Comment by MollyMcEvilley** [comment]
ref_RowPopulations.RowMax and RowMin refer to the report ROWS and not the populations.  Here we are identifying all of the subpops required for report rows 53 - 71, excluding rows 63 & 64 (which are LSAExit averages in section 8).
