### ISSUE TITLE
HDX 2.0 doesn't accept current sample results

### ISSUE THREAD

**Issue by eanders** [HMIS/LSASampleCode#735]
@MollyMcEvilley, thanks for the recent header fixes, those seem to have made the HDX happy, but we're now seeing issues with -1s in AC3PlusEST, AC3PlusPSH, and AC3PlusRRH.  Please see attached.  (These are also the only rejections I'm seeing now with a relatively small real data set
[module.upload-errors.pdf](https://github.com/HMIS/LSASampleCode/files/7364473/module.upload-errors.pdf)
.)

**Comment by MollyMcEvilley** [comment]
Commit forthcoming:

![image](https://user-images.githubusercontent.com/6156815/138299301-f1af080a-1cdf-49c4-8f3f-f0379caf7f9a.png)

I am going to go ahead and close this as I made more complete notes on #756 (and it's the same issue).
