### ISSUE TITLE
Section 9.5: Spec needs correction

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#736]
Hi @MollyMcEvilley ,

**1.**

tlsa_HHID table doesn't have next columns:
- ProjectType
- TrackingMethod

If Source will be updated, what is about their usage in sections:
- Universe and ProjectID
- Value

![image](https://user-images.githubusercontent.com/28144855/137731537-1df36ed2-d10d-402e-a248-f6cff962c356.png)

**2.** 
Maybe "cohort," should be removed because rows 56 and 57 are for single cohort = 1?
![image](https://user-images.githubusercontent.com/28144855/137732407-78ec646d-c731-4689-b485-ed62d344c6ed.png)

**3.** Is it OK that ProjectType = 3 is used twice in Spec (in restriction by MoveInDate and in restriction by EntryDate)? Because in Sample Code ProjectType = 3 is used only in restriction by MoveInDate.
![image](https://user-images.githubusercontent.com/28144855/137744137-17f7537a-8d48-4f05-8fe3-ee7daeae9c7f.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Commit forthcoming...

Q1:  I have gone through the specs and replaced **ProjectType** and **TrackingMethod** with **LSAProjectType** where appropriate.
Q2: Good point!
Q3: I removed PSH from the restriction by EntryDate.
