### ISSUE TITLE
Step 9.5.4: Universe issue

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#737]
Hi @MollyMcEvilley ,

According to the Spec, ProjectType = 3 represents Universe = 15.

But in Sample Code ProjectType = 3 is used for Universe = 14

![image](https://user-images.githubusercontent.com/28144855/137740313-e20d8eb6-2185-408d-8069-5b31d6b9fe92.png)

Could you please take a look (both SELECT and GROUP BY statements)?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!

**Comment by MollyMcEvilley** [comment]
Resolved in commit  f54b07b
