### ISSUE TITLE
Steps 9.5.1, 9.5.3, 9.5.7: hmis_Services restrictions question

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#738]
Hi @MollyMcEvilley,

In steps:
- 9.5.1
- 9.5.3 
- 9.5.7 
 
the only BedNight restriction is:
- rpt.ReportStart <= bn.DateProvided
- and rpt.ReportEnd > bn.DateProvided

1st, I wonder why ">" and not ">=" to compare rpt.ReportEnd and bn.DateProvided.
2nd, shouldn't it be any rule to exclude BedNights out of the Enrollment? If there should be any, then Spec also needs info similar to Section 3.4 but with some corrections:
![image](https://user-images.githubusercontent.com/28144855/137743269-c17774ce-3e04-4c10-b213-9309b4374d3e.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you!  Sample code has been updated and there is a commit forthcoming for the specs.  

![image](https://user-images.githubusercontent.com/6156815/138310054-07ffd61d-6673-4230-9a3c-a19c4a49eaf7.png)

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

Could you please take a look at the commit you made for this ticket? It looks like "And >=EntryDate" is missing in 2 updated places:
![image](https://user-images.githubusercontent.com/28144855/138693154-07be0334-61b8-4b62-b32c-7c34143edb51.png)

Best regards,
Natalie
