### ISSUE TITLE
Section 9.5: AHAR = 1 question (Sample Code)

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#740]
Hi @MollyMcEvilley ,

In the Spec for Section 9.5 it is said to use `tlsa_Enrollment.AHAR = 1`:
![image](https://user-images.githubusercontent.com/28144855/137756277-ac810049-f4e3-4689-b09a-4d4f038e04c0.png)

In Sample Code in some cases either `tlsa_Enrollment.AHAR = 1` or `tlsa_HHID.AHAR = 1`  is used.
`tlsa_Enrollment.AHAR = 1` is used in steps: 
- 9.5.1
- 9.5.3 (for ES NbN)
- 9.5.7 (for ES NbN)

`tlsa_HHID.AHAR = 1` is used in steps: 
- 9.5.2
- 9.5.3 (for ES E/E)
- 9.5.4
- 9.5.7 (for ES E/E)
 
![image](https://user-images.githubusercontent.com/28144855/137756637-e88c2f9d-cbec-4b16-a8ce-ba42a24f97e7.png)

Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Thank you for noticing this!  Should be n.AHAR and not hhid.AHAR in 9.5.  Commit forthcoming.
