### ISSUE TITLE
Steps 9.5.x: GROUP BY possible issue (Sample Code)

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#741]
Hi @MollyMcEvilley ,

In the Spec Section 9.5 it is said:
![image](https://user-images.githubusercontent.com/28144855/137879791-5b0dd96f-6477-48d9-9bff-73116f4c3eb3.png)

So I assume in Sample Code GROUP BY should be:
- ReportRow
- ProjectID
- Population
- Universe
- HHType

**1.**
Could you please double-check GROUP BY for:
- Step 9.5.1
- Step 9.5.2

It looks like you need to add ReportRow to the GROUP BY. Also, could you please make GROUP BY identical for both Step 9.5.1 and Step 9.5.2? Thank you!
![image](https://user-images.githubusercontent.com/28144855/137880416-cd281846-da06-4d28-a56f-8f6ea6a401c0.png)

**2.**
We also need ReportRow be included in GROUP BY for:
- Step 9.5.3
- Step 9.5.4
- Step 9.5.7

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
MSSQL doesn't require it because the grouping by ReportRow is implicit / strictly dependent on the PopID and less specific... Is it a requirement in your DB type?

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

It is perfectly enough! I will close this ticket.
