### ISSUE TITLE
Section 10.2: minor changes for Spec

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#742]
Hi @MollyMcEvilley ,

**1.**
I wonder why hardcoded **Universe** was not included in Logic section as "See above table for Cohort, **Universe**, HHType, Population, and SystemPath." text. 
![image](https://user-images.githubusercontent.com/28144855/137886565-df020073-60a7-4deb-9007-9db8428dd6d8.png)

**2.**
**2.1.** The report uses tlsa_Enrollment table that already includes `hmis_Project.ContinuumProject = 1` validation, so there is no need to check hmis_Project.ContinuumProject again.
**2.2.** Source section refers to tlsa_Enrollment table, but Logic section uses hmis_Enrollment table, not tlsa_Enrollment table.
**2.3.** I believe that the restricitons by Exit.ExitDate were shifted on purpose, correct?
**2.4.** EnrollmentCoC restriction - why do we need it here? It is also not included in the Spec.
![image](https://user-images.githubusercontent.com/28144855/137891364-6f6bf4b8-04d0-4958-afea-0ad8f3229baf.png)

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
1.  Added **Universe** in the specs.
2.1  I removed the reference to _ContinuumProject_ = 1 and EnrollmentCoC.
2.2  Corrected the Logic section to align to the Source section (and the sample code, which counts EnrollmentIDs in tlsa_Enrollment).
2.3 Re-ordered to make it clear that the ExitDate/ReportRow criteria are either/or and the other criteria are AND.
![image](https://user-images.githubusercontent.com/6156815/139110359-bd3c9893-39e5-4dbb-9de0-562bd902159d.png)
