### ISSUE TITLE
6.7 - schema and "Relevant Data Source" table need corrections (follow-up for #540)

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#746]
Hi @MollyMcEvilley ,

Last year #540 was closed, but Spec wasn't updated. Could you please take a look?

![image](https://user-images.githubusercontent.com/28144855/138041288-173e7d0e-9e81-4a3f-a816-bf43b863ee11.png)

1. “hmis_Exit” is not used. Should be removed from schema.
2. “tlsa_Enrollment” is not used. Should be removed from both schema and the “source“ table.
3. tlsa_HHID.Active is used in sample code. Should be added to the “source“ table.
4. tlsa_HHID.HouseholdID is not used. Should be removed from the “source“ table.

Thank you!
Natalie

**Comment by kiadso** [comment]
thanks, Natalie! commit forthcoming!
