### ISSUE TITLE
6.6 - schema and "Relevant Data Source" table need corrections

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#747]
Hi @MollyMcEvilley ,

This ticket is a follow-up for #539:
![image](https://user-images.githubusercontent.com/28144855/138043710-532aebd9-b44a-41ce-a251-48c58b3fefd7.png)

1. `tlsa_HHID.Active` is missing
2. `tlsa_HHID.HouseholdID` is not used in sample code and should be removed from the “Source" table
3. `hmis_Enrollment.PersonalID` should be added to the “Source" table
4. `tlsa_Enrollment.PersonalID` and `tlsa_Enrollment.HouseholdID` are not used in sample code and should be removed from the “Source" table
5.  `tlsa_Enrollment.EntryDate` should be added

Best regards,
Natalie

**Comment by kiadso** [comment]
thanks! commit forthcoming!
