### ISSUE TITLE
3.4 - "Relevant Data Source": "lsa_Report" table is missing

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#753]
Hi @MollyMcEvilley ,

Follow-up for #523: lsa_Report is missing in “Source“ table

![image](https://user-images.githubusercontent.com/28144855/138050705-1062e6f8-d67e-471e-ba8b-15d431925b2f.png)

Could you please take a look?

Thank you!
Natalie

**Comment by kiadso** [comment]
Hi, thanks, commit forthcoming!
