### ISSUE TITLE
AC3Plus update question (Sample Code after step 5.13)

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#756]
Hi @MollyMcEvilley ,

In the Spec Section 5.13 it is said:

_The AC3Plus(EST/RRH/PSH) population is limited to the AC household type, so these columns are set to 1 if there is any enrollment matching the criteria and **0 if there is not**.
For all other columns, ..._
![image](https://user-images.githubusercontent.com/28144855/138117970-c6df9276-7d51-440c-b6ae-6f05c677dd06.png)

Could you please take a look if the Sample Code should be corrected? Because not -1 is used for AC3Plus fields:
![image](https://user-images.githubusercontent.com/28144855/138118330-6c5eafb5-e7ca-4798-9835-ccc8b24ebaa1.png)

Maybe it is the reason of the issue @eanders reported in #735?
Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Commit forthcoming:

![image](https://user-images.githubusercontent.com/6156815/138299301-f1af080a-1cdf-49c4-8f3f-f0379caf7f9a.png)

Adding the HDX 2.0 label because this will have to be updated there and in the LSA Dictionary.

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley,

As I understand, LSA Data Dictionary FY2021.xlsx should also be updated (last time it was updated on 8/16/2021). Could you please take a look?

Thank you!
Natalie
