### ISSUE TITLE
Section 7.4 - discrepancy between Spec and Sample Code

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#758]
Hi @MollyMcEvilley ,

**1.**
Sample Code has step 7.4.1. Cannot find it in Section 7.4 in the Spec. Could you please take a look?

**2.**
Sample Code step 7.4.2 inserts CHTime, CHTimeStatus values in tlsa_ExitHoHAdult table. But in the Spec both CHTime, CHTimeStatus are not bold, and there is no logic described.

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/138274105-fc3a364e-80b1-4bb9-b97b-8de644abb49a.png)
**Spec:**
![image](https://user-images.githubusercontent.com/28144855/138274117-f325a934-abb4-4371-925a-c891a653b990.png)

**3.**
Sample Code uses CohortStart, but CohortStart is not listed in the Source table:
![image](https://user-images.githubusercontent.com/28144855/138274464-756cee32-db30-44cc-98f6-689145e6ca78.png)

**4.**
Sample Code uses `case when n.DisabilityStatus = 1 then 1 else 0` rule. Maybe Spec should be updated to include DisabilityStatus = 0 condition as well? Now it says `Set DisabilityStatus = 1 if tlsa_Enrollment.DisabilityStatus = 1.`
![image](https://user-images.githubusercontent.com/28144855/138276709-ce4489ff-18c1-4ab1-8a49-c897e0cd6c6f.png)

Could you please take a look?

Thank you!

**Comment by MollyMcEvilley** [comment]
1.  Add this parenthetical to the specs to make the the logic behind 7.4.1 more explicit.
![image](https://user-images.githubusercontent.com/6156815/139111224-629687bb-18f6-43db-bae9-970f4485db47.png)
2.  This was addressed in a previous issue / corrected in an earlier commit:
![image](https://user-images.githubusercontent.com/6156815/139111451-18a51a23-90f4-46cf-a2c8-47b929720384.png)
3.  There is no difference in the end result here, so I'm going to leave this alone. 
4. There's no difference in the end result here -- no person-level reporting on DisabilityStatus -- so I'm going to leave this alone.
