### ISSUE TITLE
Step 7.4.2: CohortEnd question 

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#760]
Hi @MollyMcEvilley ,

Spec checks that `ExitDate >= CohortStart` but Sample Code has also additional `ExitDate <= CohortEnd` restriction.
**Spec:**
![image](https://user-images.githubusercontent.com/28144855/138275817-7ca19e1e-1033-4796-8387-ed34da7020f5.png)

**Sample Code:**
![image](https://user-images.githubusercontent.com/28144855/138275909-864c1be8-b1e6-4379-9491-472100cdcf97.png)

I believe there is no issue, but shouldn't the restriction be the same?

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
You are correct that there is no effective difference between the two WRT end result, so I am going to leave this alone.
