### ISSUE TITLE
Step 7.4.2: LastActive question

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#762]
Hi @MollyMcEvilley ,

Here is a part of spec:
![image](https://user-images.githubusercontent.com/28144855/138278540-79694db1-0ae9-4df3-82c6-55435114eb1b.png)

**1.** What exactly fields are hidden by "chronic homelessness"? Are they all tlsa_ExitHoHAdult fields? If yes, then it makes sense that you use step 7.4.1. But if  "chronic homelessness" is CHStart only, then it is not correct to apply `ex.HHChronic is null` in step 7.4.2. Please advise.

**1.** From the spec it is not obvious from which table `EntryDate`, `ExitDate`, and `MoveInDate` should be used. We have them in both `tlsa_HHID` and `tlsa_Enrollment`.
Sample Code uses `tlsa_HHID` table, but this table is not listed in Source section (Spec).
Also, `EntryDate` is not in Source section at all.

Please advise.

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
7.4.1 - **HHChronic** = 0 is set based on tlsa_HHID entry/exit/move-in dates.  I added tlsa_HHID to the list of Source tables and clarified this in the specs.  
![image](https://user-images.githubusercontent.com/6156815/138936286-dcf3cc55-bdf8-4280-be73-fb711f9429ee.png)
7.4.2 - For the **HHChronic** = 0 records in tlsa_Exit, we don't need to go through any of the CH determination process in 7-5-7.8, so it's appropriate to exclude them ('WHERE es.HHChronic is NULL') in 7.4.2.

(Commit forthcoming.)

**Comment by MollyMcEvilley** [comment]
This update / clarification has been committed and is in the current version of the specs... I failed to note that the commit closes this issue.  ![image](https://user-images.githubusercontent.com/6156815/139119235-9bd3407a-cc52-41b7-826a-1f80dec32ee5.png)
