### ISSUE TITLE
Section 7.4: missing instructions for CHTime, CHTimeStatus

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#763]
Hi @MollyMcEvilley ,

I cannot find programming instructions for CHTime, CHTimeStatus in Section 7.4. Could you please take a look?

Thank you!
Natalie

**Comment by MollyMcEvilley** [comment]
Commit forthcoming!  

![image](https://user-images.githubusercontent.com/6156815/138939520-ea468028-2379-414d-833b-dde60df8d4fb.png)
