### ISSUE TITLE
2.5 Table creation question

### ISSUE THREAD

**Issue by 2008zjqc** [HMIS/LSASampleCode#768]
Hi Molly,
In the lsa_Inventory creation definition part, should the part' BedInventory as XXX+XXX+XXX+XXX' as comment? 

Best,
Chen

**Comment by MollyMcEvilley** [comment]
Hi Chen,

No -- not in MSSQL, anyway.  The intent is to create **BedInventory** as a computed column equal to the sum of the other columns... Does that break things on your end?

**Comment by 2008zjqc** [comment]
> Hi Chen,
> 
> No -- not in MSSQL, anyway. The intent is to create **BedInventory** as a computed column equal to the sum of the other columns... Does that break things on your end?

Hi Molly, 
If that is the case, we are also use MSSQL. I will double check with the team. You may close this one for now. Thanks very much for your quick response.
Best,
Chen

**Comment by MollyMcEvilley** [comment]
Thank you!
