### ISSUE TITLE
Steps 7.6.x: possible changes for Sample Code 

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#769]
Hi @MollyMcEvilley ,

If Section 7.6 is for qualified exits, then maybe you need to remove `or chn.ExitDate is null` condition from steps:
- 7.6.1
- 7.6.2
- 7.6.3

Also, in these steps `and ha.CHTime is null` restriction is used, but `CHTime` is not listed in Section 7.6 in the Spec.

Best regards,
Natalie

**Comment by nataliesus** [comment]
Hi @MollyMcEvilley ,

**1.**
"or chn.ExitDate is null" was removed from the Sample Code, but it still exists in the Spec that cause the discrepancy between Sample Code and Spec.
![image](https://user-images.githubusercontent.com/28144855/139041830-1635457f-3bd1-4ada-869c-25fc475af8ed.png)

**2.**
Just in case, there is one redundant "or" left in the Spec after the recent update.
![image](https://user-images.githubusercontent.com/28144855/139040976-2c6015dd-db0e-4366-917b-2c9df3c6a5d3.png)

Please let me know if I should create a new ticket.

Best regards,
Natalie

**Comment by MollyMcEvilley** [comment]
No need for a new ticket -- fixed both of these and they will be in the next commit for the specs.

Thank you!!
