### ISSUE TITLE
Does Order By Matter In 6.6

### ISSUE THREAD

**Issue by jbloescw** [HMIS/LSASampleCode#770]
https://github.com/HMIS/LSASampleCode/blob/2fd06b77783462a508d963057f78150d986d34ff/06%20LSAHousehold.sql#L242-L274

On the last line in the where statement, there is the following:  ORDER BY hhid.EntryDate ASC
I've noticed that there are a couple records fighting with each other due to them both having the same entry date and meeting all the other conditions.  This results in the "Select Top 1" to possibly bring back a different result than what is in the sample export.
Should there be an additional sort in there by program type or something?
OR does this not matter at all because the test data can not happen in real life?  (Both of the clients are enrolling into different projects/types on the same day)  This question can also apply to 6.6.2 and 6.6.3.

See EnrollmentIDS 
181681
181684

181693
181696

**Comment by MollyMcEvilley** [comment]
If the HoH has more than one enrollment into a project group on the same day, it doesn't matter which gets chosen -- we don't have any defined logic to prioritize them.
