### ISSUE TITLE
Spec: some corrections needed after ProjectType was replaced with LSAProjectType

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#772]
Hi @MollyMcEvilley ,

You did a really great job updating Spec with LSAProjectType! Thank you! Could you please take a look at a few more places if they also should be updated?

**1.** Section 3.  tlsa_HHID and tlsa_Enrollment tables do not include ProjectType, instead, they use calculated LSAProjectType
![image](https://user-images.githubusercontent.com/28144855/139057902-4fd79e30-9384-41d7-9cb5-3ce99d71d6ec.png)

**2.** Section 4.5. Target table has a referent to a table that is not described in Source section.
![image](https://user-images.githubusercontent.com/28144855/139058588-3ead68a0-cff7-46a5-b4ed-620d6b9476c2.png)

**3.** Section 7.2. "ProjectType" column name should be changed to "LSAProjectType"
![image](https://user-images.githubusercontent.com/28144855/139058775-6ad5de05-4ef8-42fd-af96-16eb751d68e2.png)

**4.** Section 9.2. It looks like `in (1,2,8)` should be replaced with `in (0,1,2,8)`
![image](https://user-images.githubusercontent.com/28144855/139059404-831204b0-d346-4836-b081-e4fccaf19335.png)

**5.** Section 11. Maybe "From lsa_Project" should be replaced with something else? Because `lsa_Project` table does not have `LSAProjectType` column
![image](https://user-images.githubusercontent.com/28144855/139061268-8d6011fc-308b-42d4-a42e-48bfd7fcdfd1.png)

Not exactly related, but maybe you can take a look?

**6.** Section 10.2. Target and Logic sections refer to `Project` table, but isn't it `hmis_Project` table? Also, Project.ProjectID is not listed in the Source section.
![image](https://user-images.githubusercontent.com/28144855/139060245-a2bf52b4-df34-4a26-bd61-10f131723efb.png)

**7.** Section 10.3. Target and Logic sections refer to `Project` table, but isn't it `hmis_Project` table?
![image](https://user-images.githubusercontent.com/28144855/139060538-36d3f1ba-a4de-498c-bf64-47283e7aa3da.png)

**8.** Section 10.4. Should `Project.ProjectID` be replaced with `lsa_Project.ProjectID`? Also, ` `lsa_Project.ProjectID` is not listed in the Source table.
![image](https://user-images.githubusercontent.com/28144855/139060771-13392f5c-3327-4cd1-bc91-3088354580a1.png)

Thank you!

**Comment by nataliesus** [comment]
Also, section 3.1 refers to `Project` table that should be `hmis_Project` table.
![image](https://user-images.githubusercontent.com/28144855/139061992-78e4246a-9e2e-43fd-aeae-ce16c5ea7bb6.png)
Maybe you will find more places.

**Comment by nataliesus** [comment]
Also, "TrackingMethod" should be replaced from tables where "LSAProjectType" is used.

**9.** Section 3.4
![image](https://user-images.githubusercontent.com/28144855/139063395-202a779b-4cf4-4434-a514-d4a86b43a8c4.png)

**10.** Section 6.13
![image](https://user-images.githubusercontent.com/28144855/139063576-e323f86e-60c6-4640-991e-82866819d226.png)

**Comment by MollyMcEvilley** [comment]
1. Fixed in specs section 3
2. This is a place where the HDX is enforcing a DQ rule that the HMIS CSV doesn't include -- in contrast to the "see HMIS CSV documentation in other columns" -- so the reference is to Project.csv and not lsa_Project or hmis_Project...  
3. Fixed in specs section 7.2 
4. Fixed in specs section 9.2
5. Clarified in specs that **LSAProjectType** comes from the combination of lsa_Project.**ProjectType** and **TrackingMethod**.
6. (also 7 and 8) This is a place where the HDX is enforcing a DQ rule that the HMIS CSV doesn't include, so the reference is to Project.csv and not lsa_Project or hmis_Project. I should clarify this in the specs in general... 
9.  Fixed in specs section 3.4.
10. Fixed in specs section 6.13.
