### ISSUE TITLE
Spec needs layout corrections

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#776]
Hi @kiadso ,

Could you please:
1) re-generate "Table of Contents"? Clicking on section 7.5 section 7.6 is opened.
2) After last updates, 7.5 section title disappeared.
3) Do you also see overlapping blocks of text and schemas as I see them (screenshot) or it is something wrong on my side?
![image](https://user-images.githubusercontent.com/28144855/139225090-7e0492ae-9009-470c-a392-3ebf202998fc.png)
4) if point 3 is true for you, then could you please review the whole document as there were more than 1 place to fix overlapping blocks issue
5) It looks like sections were somehow shifted because old 7.5 is now 7.6.
![image](https://user-images.githubusercontent.com/28144855/139226335-5a602cdd-0bde-403b-b249-d73c12931380.png)

Best regards,
Natalie

**Comment by nataliesus** [comment]
I think it is because I had "Show tracked changes" enabled. When I disabled this option, numeration restored, but now there are empty rows in source tables i.e.
![image](https://user-images.githubusercontent.com/28144855/139227825-efa5a06d-e337-4878-ab53-36ea6af0b62e.png)
Please advise.

BTW, do you still need "LSA Programming Specifications FY2021 Annotated.docx"? or it will be deleted soon?

**Comment by nataliesus** [comment]
Shouldn't "and" be moved to the prev rows?
![image](https://user-images.githubusercontent.com/28144855/139228241-93fcbcf9-4258-4694-9436-4251724cbdb4.png)

**Comment by kiadso** [comment]
All these are cleared up now that Track Changes things have been done, plus moving the "and"s. Commit forthcoming
Thanks Natalie
