### ISSUE TITLE
Section 6.6 - 2 schemas instead of 1

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#780]
Hi @kiadso ,

Could you please take a look and remove one extra schema?

![image](https://user-images.githubusercontent.com/28144855/139232618-af8df0b5-485c-452a-8a66-b589d259fed4.png)

Also, should it be any row between schema blocks?

Thank you!
Natalie

**Comment by kiadso** [comment]
resolved by accepting Track Changes on images, commit forthcoming
