### ISSUE TITLE
Section 6.7 - 2 schemas instead of 1

### ISSUE THREAD

**Issue by nataliesus** [HMIS/LSASampleCode#781]
Hi @kiadso ,

Do you also see two schemas?
![image](https://user-images.githubusercontent.com/28144855/139233174-8a16e3b8-ca58-43de-8c28-25420a1ca901.png)

If yes, please remove extra one.

Thank you,
Natalie

P.S. could you please review the whole spec just in case there is no or more than 1 schemas in other sections?

**Comment by kiadso** [comment]
Yes, will review this morning! I had the document showing "no markup", that
is probably the problem

Genelle
she/her/hers

**Comment by kiadso** [comment]
Confirmed, this screenshot was in Track Changes "all markup". I accepted all the edits around schemas and the former schema is no longer showing. Commit forthcoming.
